### ISSUE TITLE
resolve wrong path for external modules

### ISSUE THREAD

**Issue by frux** [wbyoung/babel-plugin-transform-postcss#23]
### Code of my component
``myproject/components/super-component/index.jsx``
```js
import 'external-module/styles.css';
import styles from './my-local-styles.css';

// ...
```
### Babel config
``.babelrc``
```json
{
    "presets": ["es2017-node7", "react"],
    "plugins": ["transform-postcss"],
    "ignore": ["node_modules"]
}
```

And I get an error:
```
babel-plugin-transform-postcss: Error: ENOENT: no such file or directory, open '/Users/frux/myproject/components/super-component/external-module/external-module/styles.css'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at Socket.connection.on (/Users/frux/myproject/node_modules/babel-plugin-transform-postcss/dist/postcss-server.js:81:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Why does plugin try to find external styles at relative path?

**Comment by wbyoung** [comment]
Yeah, that's not a case that has been considered yet.

It'd probably work ok with modules that use the `postcss.config` setup, but really modules should be publishing compiled CSS that doesn't need to be run through CSS modules or PostCSS.

Can you elaborate on your use case and the external module you're using (if its public)?

**Comment by frux** [comment]
Unfortunately it's not. But I guess it's not something extraordinary. It's a simple library of react components which consists of compiled ``js`` and ``css`` files so I don't need to process it by your plugin. I just want to use css-modules everywhere in my project except of ``node_modules`` (because external components are already compiled) so I asked babel to ignore ``node_modules`` in my ``.babelrc``. But ``babel-plugin-transform-postcss`` thinks it's not external and still trying to process it.

**Comment by wbyoung** [comment]
The best option at this point may be to include it via a relative path. Either:

```js
import './node_modules/external-module/styles.css';
```

Or create a symbolic link so you don't need to include `node_modules`:

```js
import './vendor/external-module.css';
```

I'd consider a PR that addresses this issue, but it kind of seems like a Pandora's box at this point. I'm not sure the PostCSS community has standardized enough around what/how _modules_ should be published at this point to really make it worthwhile to try to solve this right now, so I'm going to close the issue, but am still interested in having further discussion now and/or in the future regarding what it would mean to address this shortcoming.
