### ISSUE TITLE
Webpack ExtractTextPlugin stops working after using transform plugin

### ISSUE THREAD

**Issue by max-mykhailenko** [wbyoung/babel-plugin-transform-postcss#53]
Did plugin remove import statement from code? How I can leave my extracting logic?

**Comment by wbyoung** [comment]
I don't know what that plugin does and am not using this in a Webpack setup. Can you post an example project without `babel-plugin-transform-postcss` to GitHub and then open a PR against that working example that shows how and what exactly is breaking?

**Comment by max-mykhailenko** [comment]
Not needed more, moving to webpack on server side
