### ISSUE TITLE
How to make CSS modules random hashmaps match?

### ISSUE THREAD

**Issue by FezVrasta** [wbyoung/babel-plugin-transform-postcss#60]
I think I'm missing something on how we are supposed to use this plugin and CSS Modules.

If I make this plugin generate CSS modules, or better, transform my classes (`.foo`) into random names (`.foo_xyz123`).

How can I then process my PostCSS to compile it into valid CSS having the classes transformed the same way? (`.foo` to `.foo_xyz123`)

Wouldn't be easier to support an extract option like [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform#extract-css-files)?

**Comment by wbyoung** [comment]
@FezVrasta the idea would be to have the class names be non-random and instead based on something (like the file path or file contents) & just hash that to generate something that appears random, but isn't.

Generally, this is how examples are configured.

Extracting CSS means adding a lot of complication that other tools cover (generating the CSS), and the use of a shared config file makes it so this shouldn't really be needed — except in the case of truly random class names.

If you want truly randomized class names, you won't be able to use this plugin.
