### ISSUE TITLE
Keeping import declaration

### ISSUE THREAD

**Issue by morulus** [wbyoung/babel-plugin-transform-postcss#88]
Hi. In another similar package called [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform), one day, I've added the feature `keepImport`, which allows do not remove the import declaration, after all transformations. It was a good time, until I found your package more useful. But your package also has no opportunity to keep import declaration. Therefor, I'm going to perform that for you.

Here's description of the coming feature. I hope you will found it useful.

## Keeping import

By default, original import declaration in javascript code will be replaced with an object with styles. But you may keep import declarations by turning the option `keepImport` to `true`.

```json
{
  "plugins": [
    ["transform-postcss", {
      "config": "configuration/postcss.config.js",
      "extensions": [".scss"],
      "keepImport": true
    }]
  ]
}
```

In this case, you will still get the required objects with styles, but import declarations (or require expressions) will be kept above without any assignment expression.

For example, this code:

```js
import styles from './styles';
```

```css
.example { color: cyan; }
```

Will be transformed to:

```js
import './styles';
var styles = {"example":"_example_amfqe_1"};
```

**Comment by wbyoung** [comment]
Out of curiosity: what's the use case here? I'm can't think of a case where keeping the import would matter.

**Comment by morulus** [comment]
As I understand, your module is used mainly for server-side rendering. And styles, in this case, are connected separately. My goal is to import styles with a style-loader, but at the same time with precompiled modules.
For example, I can prepare UI component as npm package, which will have precompiled styles and precompiled javascript code (that will already have class names hashmaps). Next, all I need, as a user of that package, is to require it from my source code. And all styles will be imported automatically. Without `keepImport` I would have to import styles manually.

**Comment by wbyoung** [comment]
@morulus I'm still not sure I understand. What advantage is there to importing a `.css` file that can't be used. The whole point of the module is to remove those imports and replace them with something usable. Can you post a set of example projects that actually shows what you're trying to accomplish?

**Comment by morulus** [comment]
> The whole point of the module is to remove those imports and replace them with something usable

But classnames hashmap is useless without CSS file itself. The question is how are you gonna to import target CSS file to your HTML page? Especially if there are many CSS files.

For example, we have a some widget, called `awesome-widget`. And here is the project's filesystem structure:
```
package.json
lib
src
├── index.es
├── styles.css
│   ├── themes
│   │   ├── alfa.css
│   │   ├── beta.css
```

And here's code of _index.es_:

```js
import defaultStyles from './styles.css';
import alfaTheme from './themes/alfa.css';
import betaTheme from './themes/beta.css';

const themes = {
  alfa: alfaTheme,
  beta: betaTheme
}

export default ({
  theme
}) => (
  <div className={(themes[theme] || defaultStyles).main}>Hello, React</div>
)
```

To compile this files to the folder `lib` I use babel with plugin `postcss-transform`. And here's what I got:

```js
const defaultStyles = {...};
const alfaTheme = {...};
const betaTheme = {...};

const themes = {
  alfa: alfaTheme,
  beta: betaTheme
}

export default ({
  theme
}) => (
  React.createElement('dev', {className: (themes[theme] || defaultStyles).main}, 'Hello, React')
)
```

Ok. Now, I need to compile three CSS files. And I use `gulp-postcss` with the same plugins, and `gulp-concat-css` to join all these CSS files into one stylesheet.

And here's result:

```
package.json
lib
├── index.js
├── styles.css
src
├── index.es
├── styles.css
│   ├── themes
│   │   ├── alfa.css
│   │   ├── beta.css
```

Looks great.

Now, I publish it to the npmjs.org (`npm publish`). Now, my package `awesome-widget` can be installed from npm.

In another project, created with [CRA](https://github.com/facebook/create-react-app), I'd like to use my awesome widget.

In some file I wrote:

```js
import AwesomeWidget from 'awesome-widget';

export default () => (
  <AwesomeWidget theme="alfa" />
)
```

And what I see... Omg. Where are my styles? The problem is that `styles.css` do not imported. Probably I need to import styles manually to make it works correctly.

```js
import AwesomeWidget from 'awesome-widget';
import AwesomeWidget from 'awesome-widget/lib/styles.css';

export default () => (
  <AwesomeWidget theme="alfa" />
)
```

Now it works. But, It does not look ergonomic! It is not comfortable to import styles manually each time I'd like to use my widget. I'm sad...

But, wait! Why can not styles files be imported automatically? Maybe all I need is to keep the import statement in javascript files of my widget! 💡

I enables `keepImport` option in plugin `transform-postcss` and I removes `gulp-concat-css` from my gulp chain (I don't need it anymore). And now I have `index.js`, which looks like follow:

```js
import './styles.css';
const defaultStyles = {...};

import './themes/alfa.css';
const alfaTheme = {...};

import './themes/beta.css';
const betaTheme = {...};

const themes = {
  alfa: alfaTheme,
  beta: betaTheme
}

export default ({
  theme
}) => (
  React.createElement('dev', {className: themes[theme] || defaultStyles}, 'Hello, React')
)
```

After these transformations, I easily can use a single import.

```js
import AwesomeWidget from 'awesome-widget';

export default () => (
  <AwesomeWidget theme="alfa" />
)
```

And, it works. I do not need to import stylesheets manually. The `style-loader` of webpack really did import these styles. It's convenient. The points are that all my CSS classnames have been isolated (by postcss-modules) and in the same time I do not need to configure my bundle system to compile CSS again and I do not need to import styled manually. Looks perfect.

Is the concept clear?

**Comment by wbyoung** [comment]
Ok, I think this is already possible via #28.

**Comment by wbyoung** [comment]
Also, I'm not quite sure that this type of problem should be solved in this type of plugin or that the solution you're proposing is the "right" one. For individuals, expecting that type of dependency may be okay, but for the broader ecosystem, that doesn't seem like the right call. I think I commented on this at some point before, but couldn't find the comment.

As I understand it, this would force consumers of your awesome widget to use a build system that understood these imports/require statements. That runs against the common practice for JS modules of publishing transpiled modules. Imagine an ecosystem where packages published untranspiled code and you tried to combine a lot of them — either everyone agrees that there's _one_ system and keeps in sync or something needs to be _really_ good at handling _every single possible combination_ of pre-transpiled code and combining them.

This same thing applies to CSS since you can use any number of combination of tools to pre-process CSS. Pushing the pre-processing of the CSS down to the consumer to me feels completely wrong. If anything, it seems as though support for that should live elsewhere.

Even if your awesome widget keeps the imports, you're still probably dealing with non-widget based CSS for which your main app has to account for (i.e. `react` itself, `jquery`, or `some-not-so-well-known-project-that-not-everyone-uses`). You need a way to pull in arbitrary CSS from external modules. So far I haven't really seen anything that handles this gracefully (though I haven't tried webpack yet). Widgets just don't really feel like a special case to me.

So I guess this is the long way of me saying that I philosophically disagree. I'm open to more discussion or even being shown that the community has moved in a certain direction on this where a consensus has been reached.

**Comment by morulus** [comment]
Popular tools (based on webpack) like [Create react app](https://github.com/facebook/create-react-app), [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) handle require CSS statements inside the javascript code of packages placed in _node_modules_ just fine.

I'm afraid I don't have time for further discussions. The problem is that you philosophize at all. Your plugin work is not about how to conceptually do the right things or what are the moral standards of widgets, but just an apathetic tool to achieve some compilation results!

Despite you philosophical views, the technique of keeping `require` statements already works and makes a profit for us. I just wanted to share a useful way but does not ask for a philosophically manifesto on how widgets should work, especially since you for some reason think that your plugin can only be used to create public components on npm, where they will need to be sold to consumers.

https://github.com/wbyoung/babel-plugin-transform-postcss/pull/28 - It's not even close. Sorry, it seems you do not understand.

**Comment by jared-hexagon** [comment]
Chiming in here - I assumed this plugin would do this by default.

I want to ship my CSS modules with my library and import them inside each JS file. It does mean the consumer needs to load my CSS files somehow but tools like webpack make that easy with css-loader, file-loader, etc.. Tools like create-react-app do this. I just need to get the generated class names out of it so I can use them in my JS (React components).

**Comment by morulus** [comment]
@jared-hexagon That's what I've talked about. That's the case.

**Comment by morulus** [comment]
@jared-hexagon If you have any questions about this functionality, you can ask me, because it is already solved for me.

**Comment by jared-hexagon** [comment]
@morulus I would love to know how you solved it. I have tried a bunch of Babel and PostCSS plugins but no success.

**Comment by morulus** [comment]
@jared-hexagon Use this fork https://github.com/morulus/babel-plugin-transform-postcss
It has keepImport functionality support. And it works just like I've described at the top of this topic:

```
{
  "plugins": [
    ["transform-postcss", {
      "config": "configuration/postcss.config.js",
      "extensions": [".scss"],
      "keepImport": true
    }]
  ]
}
```


But it was not published in the npm, so you should use some local npm registry or another way to prepack it.

Also, I found a real problem with the babel-plugin-transform-postcss as a whole when working with a large number of assemblies at the same time. Because it uses some kind of temporary files in OS root filesystem, these able to create the collisions. But this is a different topic.

**Comment by jared-hexagon** [comment]
@morulus That fork works really well except for a small issue. I can't raise issues with your fork - can you please enable them?

**Comment by morulus** [comment]
@jared-hexagon issues are aviable now
